name: Terraform Deploy

on:
  push:
    branches:
      - dev
      - main
    paths:
      - "terraform/**"
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'prod' || 'dev' }}

    defaults:
      run:
        working-directory: terraform

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Authenticate GCP
        uses: google-github-actions/auth@71f986410dfbc7added4569d411e0402515e52b2 # v2.1.8
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_QWINTLY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e424188331551155026903a # v3.1.2

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ vars.TF_STATE_BUCKET_QWINTLY }}" \
            -backend-config="prefix=terraform"

      - name: Terraform Plan
        env:
          GCP_PROJECT_ID_QWINTLY: ${{ vars.GCP_PROJECT_ID_QWINTLY }}
          GCP_PROJECT_ID_GEN_SITES: ${{ vars.GCP_PROJECT_ID_GEN_SITES }}
          REF_NAME: ${{ github.ref_name }}
          WORKER_PUSH_ENDPOINT: ${{ vars.WORKER_PUSH_ENDPOINT }}
        run: |
          terraform plan \
            -var="project_id=$GCP_PROJECT_ID_QWINTLY" \
            -var="generated_sites_project_id=$GCP_PROJECT_ID_GEN_SITES" \
            -var="environment=${{ github.ref_name == 'main' && 'prod' || 'dev' }}" \
            -var="webgen_push_endpoint=$WORKER_PUSH_ENDPOINT"

      - name: Terraform Apply
        env:
          GCP_PROJECT_ID_QWINTLY: ${{ vars.GCP_PROJECT_ID_QWINTLY }}
          GCP_PROJECT_ID_GEN_SITES: ${{ vars.GCP_PROJECT_ID_GEN_SITES }}
          REF_NAME: ${{ github.ref_name }}
          WORKER_PUSH_ENDPOINT: ${{ vars.WORKER_PUSH_ENDPOINT }}
        run: |
          terraform apply -auto-approve \
            -var="project_id=$GCP_PROJECT_ID_QWINTLY" \
            -var="generated_sites_project_id=$GCP_PROJECT_ID_GEN_SITES" \
            -var="environment=${{ github.ref_name == 'main' && 'prod' || 'dev' }}" \
            -var="webgen_push_endpoint=$WORKER_PUSH_ENDPOINT"
